### ISSUE TITLE
Keep Advantages

### ISSUE THREAD

**Issue by rtbbase-helper** [Planteome/CO_331-sweetpotato-traits#24]
## Submitter

|             |                     |
| ----------- | ------------------- |
| **Name**    | Bryan    |
| **Program** | NCSU |

## Request

|                        |                           |
| ---------------------- | ------------------------- |
| **Trait Name**         | Keep Advantages    |
| **Definition**         | A trait to track what advantages an accession has that leads to it being selected.     |
| **Trait Class**        | Morphological   |
| **Measurement Method** | visual         |
| **Measurement Type**   | Categorical |

#### Categories

| ID       | Description |
| -------- | ----------- |
| **GoodAT** | Good Attachment    |
| **Blocky** | Blocky root shapes    |
| **Early** | Sizes up early, early maturity    |
| **GDSizeDist** | Good size distribution    |
| **HighDM** | High Dry Matter    |
| **HighSet** | Lots of roots    |
| **Proc_Only** | Not a good for fresh market, only processing    |
| **Round** | Roots are round    |
| **ShapeUnifo** | Shapes are fairly uniform    |

**Comment by cooperl09** [comment]
This is not a trait per se, but a collection of traits.

**Comment by jaiswalp** [comment]
Towards 'phenotypic acceptability'. We have http://browser.planteome.org/amigo/term/TO:0000322

**Comment by jaiswalp** [comment]
Keep Advantages = TO: phenotypic acceptability

**Comment by bellerbrock** [comment]
@cooperl09 true. It's collected this way because it is not worth the time or effort to define and record values for 9 different traits. But then unfortunately it's more of a structured comment field than a trait. 

@jaiswalp I see how it is related to phenotypic acceptabilty. I like that trait as a measure of overall acceptability independent of breeding objective. 
Unfortunately in this case it is important to the breeder to record what specific positive characteristics make the genotype stand out. That info helps inform what further tests it should be included in, and also informs crossing decisions, because it can help determine which positive traits are actually being inherited from a given parent across all it's offspring.
